### ISSUE TITLE
Wrong version mentioned in README.md

### ISSUE THREAD

**Issue by naman-scogo** [deid84/tauri-plugin-serialport#3]
[dependencies]
tauri-plugin-serialport = { git = "https://github.com/deid84/tauri-plugin-serialport", tag = "v0.1.0" }

npm install github:deid84/tauri-plugin-serialport#v0.1.0
# or
yarn add github:deid84/tauri-plugin-serialport#v0.1.0

These commands have the v0.1.0 tags which are not available.

The available tag is v1.0.0 please make the necessary changes so people don't have any issue while trying it out.

**Comment by deid84** [comment]
hi @naman-scogo thank's for your issue.

I've updated the version tag in readme.

In next days i'll push a 1.0.1 release with updated tauri dependencies.

**Comment by naman-scogo** [comment]
@deid84 Thank you for the prompt response. Looking forward to the next version also, please mention the breaking changes, if any 😄
